#define on(x) _on(x)
#define off(x) _off(x)
#define flip(x) _flip(x)
#define pullup(x) _on(x)
#define in(x) _in(x)
#define out(x) _out(x)
#define get(x) _get(x)

#define _on(bit,port) (PORT##port |= (1<<bit))
#define _off(bit,port) (PORT##port &= ~(1<<bit))
#define _flip(bit,port) (PORT##port ^= (1<<bit))
#define _in(bit,port) (DDR##port &= ~(1<<bit)) 
#define _out(bit,port) (DDR##port |= (1<<bit)) 
#define _get(bit, port) (PIN##port & (1<<bit))
